from TerminalApp import TerminalApp

if __name__ == '__main__':
    app = TerminalApp()
    app.Open("./test.md")
    app.InsertTail("# 我的书签")
    app.InsertTail("## 学习资源")
    app.InsertTail("### 编程")
    app.InsertTail("* Java从入门到入土")
    app.List()
    print("--------------------")
    app.InsertRow(3, "## 新的子标题")
    app.List()
    print("--------------------")
    app.InsertHead("# 新的标题")
    app.List()
    print("--------------------")
    app.InsertTail("* 新的文本")
    app.List()
    print("---------undo-----------")
    app.Undo()
    app.List()
    print("---------undo-----------")
    app.Undo()
    app.List()
    print("---------undo-----------")
    app.Undo()
    app.List()
    print("---------undo-----------")
    app.Undo()
    app.List()
    print("---------undo-----------")
    app.Redo()
    app.List()
    print("---------redo-----------")
    app.Redo()
    app.List()
    print("---------redo-----------")
    app.Redo()
    app.List()
    print("---------redo-----------")
    app.Redo()
    app.List()
    print("---------redo-----------")
